theme = "catppuccin_mocha_translucent"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
rulers = [80]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left=["mode", "spinner", "version-control", "file-name"]

[editor.file-picker]
hidden = false

[editor.lsp]
enable = true

[keys.normal]
"C-j" = "goto_previous_buffer"
"C-k" = "goto_next_buffer"
"A-w" = ":buffer-close"
esc = ["collapse_selection", "keep_primary_selection"]
